### ISSUE TITLE
用权限控制把r18禁用后使用看看图报错

### ISSUE THREAD

**Issue by axlmly** [bot-ssttkkl/nonebot-plugin-pixivbot#220]
单张色图只会报错,多张色图登入的qqnt直接崩溃
4-16 17:37:19 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42) failed.
Traceback (most recent call last):
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 27, in _feedback_on_action_failed
    yield
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 92, in post_illust
    await self._post(msg, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 73, in _post
    await msg.send(reply=True)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 290, in send
    return await self._do_send(bot, target, event, at_sender, reply)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 354, in _do_send
    return await sender(bot, self, target, event, at_sender, reply)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\adapters\onebot_v11.py", line 186, in send
    res_dict = await bot.send_msg(message=message_to_send, **target.arg_dict(bot))
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='文件异常，大小为0', wording='文件异常，大小为0', echo='16')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 42, in run_excepting
    yield
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 43, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\timeout_interceptor.py", line 17, in intercept
    await wait_for(wrapped_func(*args, **kwargs),
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 489, in wait_for
    return fut.result()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\loading_prompt_interceptor.py", line 24, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 28, in intercept
    raise e
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 23, in intercept
    return await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 124, in _parse_args_and_actual_handle
    await self.actual_handle(**kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 39, in actual_handle
    await self.post_illust(illust)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 217, in post_illust
    await context.require(Postman).post_illusts(model, self.session, self.event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\recorder.py", line 77, in post_illusts
    await self.delegation.post_illusts(model, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 100, in post_illusts
    await self.post_illust(x, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 85, in post_illust
    async with self._feedback_on_action_failed():
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 29, in _feedback_on_action_failed
    raise PostIllustError() from e
nonebot_plugin_pixivbot.utils.errors.PostIllustError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 47, in _
    await IllustHandler(session, event).handle(illust_id)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 111, in handle
    await self.interceptor.intercept(self, self._parse_args_and_actual_handle, *args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  [Previous line repeated 1 more time]
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\service_interceptor.py", line 35, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 42, in intercept
    async with error_handlers.run_excepting(receive_error_message, reraise_unhandled=True):
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 55, in run_excepting
    msg = handler(e)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 31, in _
    logger.exception(e)
TypeError: __str__ returned non-string (type NoneType)
上面是单张色图报的错 看看图112735119
下面是多张色图报的错 看看图97977433
04-16 17:30:14 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42) running complete
04-16 17:30:14 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 47, in _
    await IllustHandler(session, event).handle(illust_id)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 111, in handle
    await self.interceptor.intercept(self, self._parse_args_and_actual_handle, *args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  [Previous line repeated 1 more time]
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\service_interceptor.py", line 35, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 43, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\timeout_interceptor.py", line 17, in intercept
    await wait_for(wrapped_func(*args, **kwargs),
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 489, in wait_for
    return fut.result()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\loading_prompt_interceptor.py", line 24, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 28, in intercept
    raise e
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 23, in intercept
    return await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 124, in _parse_args_and_actual_handle
    await self.actual_handle(**kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 39, in actual_handle
    await self.post_illust(illust)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 217, in post_illust
    await context.require(Postman).post_illusts(model, self.session, self.event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\recorder.py", line 77, in post_illusts
    await self.delegation.post_illusts(model, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 109, in post_illusts
    await self._post(msg, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 75, in _post
    await msg.send()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 418, in send
    await self._do_send(bot, target, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 402, in _do_send
    return await sender(bot, self.message_factories, target, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\adapters\onebot_v11.py", line 217, in aggregate_send
    await bot.send_group_forward_msg(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')

qqnt版本9.9.7 llob 3.22.1

**Comment by axlmly** [comment]
看看榜指令输出全是空白,转发只有一条这是你点的日榜.来张图指令时不时就发不出去,数量到12张会出现ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。看缓存是有缓存下来,但是努力加载中后就没动静了

**Comment by axlmly** [comment]
更新llob后空消息不会导致qqnt崩溃了
04-17 03:19:06 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42)
04-17 03:19:07 [INFO] nonebot_plugin_pixivbot | [illust_detail] cache loaded  (illust_id=97977433)
04-17 03:19:07 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42) running complete
04-17 03:19:07 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.illust, lineno=42) failed.
Traceback (most recent call last):
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 27, in _feedback_on_action_failed
    yield
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 109, in post_illusts
    await self._post(msg, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 75, in _post
    await msg.send()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 418, in send
    await self._do_send(bot, target, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\utils\types.py", line 402, in _do_send
    return await sender(bot, self.message_factories, target, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_saa\adapters\onebot_v11.py", line 217, in aggregate_send
    await bot.send_group_forward_msg(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='发送转发消息失败 Error: 转发消息失败，节点为空', wording='发送转发消息失败 Error: 转发消息失败，节点为空', echo='76')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 42, in run_excepting
    yield
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 43, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\timeout_interceptor.py", line 17, in intercept
    await wait_for(wrapped_func(*args, **kwargs),
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 489, in wait_for
    return fut.result()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\loading_prompt_interceptor.py", line 24, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 28, in intercept
    raise e
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\retry_interceptor.py", line 23, in intercept
    return await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 124, in _parse_args_and_actual_handle
    await self.actual_handle(**kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 39, in actual_handle
    await self.post_illust(illust)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 217, in post_illust
    await context.require(Postman).post_illusts(model, self.session, self.event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\recorder.py", line 77, in post_illusts
    await self.delegation.post_illusts(model, session, event)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 95, in post_illusts
    async with self._feedback_on_action_failed():
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\service\postman.py", line 29, in _feedback_on_action_failed
    raise PostIllustError() from e
nonebot_plugin_pixivbot.utils.errors.PostIllustError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\common\illust.py", line 47, in _
    await IllustHandler(session, event).handle(illust_id)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\base.py", line 111, in handle
    await self.interceptor.intercept(self, self._parse_args_and_actual_handle, *args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  [Previous line repeated 1 more time]
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\service_interceptor.py", line 35, in intercept
    await wrapped_func(*args, **kwargs)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 42, in intercept
    async with error_handlers.run_excepting(receive_error_message, reraise_unhandled=True):
  File "C:\Users\xiuzh\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\ssttkkl_nonebot_utils\errors\error_handler.py", line 55, in run_excepting
    msg = handler(e)
  File "E:\BOT\nonebot\b\.venv\Lib\site-packages\nonebot_plugin_pixivbot\handler\interceptor\default_error_interceptor.py", line 31, in _
    logger.exception(e)
TypeError: __str__ returned non-string (type NoneType)

**Comment by TeamBreakerr** [comment]
我没有禁用r18也会报错TypeError: str returned non-string (type NoneType)
