### ISSUE TITLE
在调用 来两张图指令时报错

### ISSUE THREAD

**Issue by wukaka155** [bot-ssttkkl/nonebot-plugin-pixivbot#236]
10-14 19:38:26 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_recommended_illust, lineno=35) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/common/random_recommended_illust.py", line 39, in _
    await RandomRecommendedIllustHandler(session, event).handle(count=count)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/base.py", line 111, in handle
    await self.interceptor.intercept(self, self._parse_args_and_actual_handle, *args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 54, in intercept
    await self.x.intercept(
  [Previous line repeated 2 more times]
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/service_interceptor.py", line 35, in intercept
    await wrapped_func(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/default_error_interceptor.py", line 43, in intercept
    await wrapped_func(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/timeout_interceptor.py", line 17, in intercept
    await wait_for(wrapped_func(*args, **kwargs),
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/loading_prompt_interceptor.py", line 24, in intercept
    await wrapped_func(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/retry_interceptor.py", line 28, in intercept
    raise e
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/retry_interceptor.py", line 23, in intercept
    return await wrapped_func(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/interceptor/record_req_interceptor.py", line 16, in intercept
    await wrapped_func(*args, **kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/base.py", line 124, in _parse_args_and_actual_handle
    await self.actual_handle(**kwargs)
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/handler/common/random_recommended_illust.py", line 27, in actual_handle
    illusts = await service.random_recommended_illust(count=count,
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/service/pixiv_service.py", line 111, in random_recommended_illust
    illusts = [x async for x in repo.recommended_illusts()]
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/service/pixiv_service.py", line 111, in <listcomp>
    illusts = [x async for x in repo.recommended_illusts()]
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/mediator_repo.py", line 389, in recommended_illusts
    async for x in gen:
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/utils/shared_agen.py", line 62, in _generator
    raise e
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/utils/shared_agen.py", line 55, in _generator
    new_data = await self._origin.__anext__()
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/mediator.py", line 151, in mediate
    async for x in self._load_many_from_remote_and_append(query_kwargs, max_item, max_page):
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/mediator.py", line 116, in _load_many_from_remote_and_append
    async for item in self.remote_factory(query_kwargs):
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/remote_repo.py", line 249, in _get_illusts
    async for page, metadata in self._load_many_pages(papi_search_func, "illusts",
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/remote_repo.py", line 214, in _load_many_pages
    page, metadata = await self._load_page(papi_search_func, element_list_name, mapper=mapper,
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/nonebot_plugin_pixivbot/data/pixiv_repo/remote_repo.py", line 190, in _load_page
    metadata = PixivRepoMetadata(next_qs=AppPixivAPI.parse_qs(next_url=raw_result["next_url"]))
  File "/home/linyuan/miniconda3/envs/nonebot/lib/python3.9/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PixivRepoMetadata
pages
  Field required [type=missing, input_value={'next_qs': {'content_typ...7621790', '123262281']}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by zwfengineer** [comment]
> `pip list`一下 
已经修了，我push一下。

**Comment by zwfengineer** [comment]
> `pip list`一下

PixivRepoMetadata 这个类的调用中 optional 的属性也必须传入一个None才能运行
可能和pydantic更新有关系

**Comment by ssttkkl** [comment]
确实，我还没测过pydantic v2的表现（
